### ISSUE TITLE
raw type for spoiler

### ISSUE THREAD

**Issue by 33mhz** [pnut-api/object-metadata#5]

**Comment by shawnthroop** [comment]
This would be awesome! 

I've run into a feature enabled by something like this when using Apollo, my favourite reddit iOS client. What is lacking from Apollo's implementation is a way to specify the topic or description of what is being hidden. I usually have to reveal the spoiler anyways because the title is too vague. 

Being able to supply some non-spoilerific text would be awesome. Then clients could use that to instead show something like: "Tap to reveal Star Wars spoilers".

**Comment by 33mhz** [comment]
For post and message types:
```json
{
  "type": "shawn.spoiler",
  "value": {
    "topic": "Star Trek: DS9",
    "expired_at": "2018-04-27T13:02:56Z"
  }
}
```

`expired_at` would be optional.
